"""
Script planning support for SDMXerWizard.

The transformation script itself is written by the calling model. This file
provides the deterministic material it works from: script templates, ordered
transformation steps built from a mapping result, loading snippets, and a
light syntactic check of a finished script.
"""

# Dependencies loaded at package level


"""
    TransformationStep

Represents a single step in a data transformation pipeline for SDMX processing.

This struct encapsulates all information needed to generate a single transformation
operation in a Tidier.jl script, including the operation type, validation checks,
and descriptive comments for the generated code.

# Fields
- `step_name::String`: Descriptive name for this transformation step
- `operation_type::String`: Type of operation ("read", "mutate", "pivot", "filter", "validate", "write")
- `tidier_function::String`: Tidier.jl function to use ("@mutate", "@pivot_longer", etc.)
- `description::String`: Human-readable description of what this step does
- `source_columns::Vector{String}`: Input columns required for this step
- `target_columns::Vector{String}`: Output columns produced by this step
- `transformation_logic::String`: The actual transformation code/expression
- `validation_checks::Vector{String}`: Validation checks to include
- `comments::Vector{String}`: Additional comments for code documentation

# Examples
```julia
step = TransformationStep(
    "Recode Country Values",
    "mutate",
    "@mutate",
    "Maps source country names to SDMX GEO_PICT codes",
    ["country_name"],
    ["GEO_PICT"],
    "GEO_PICT = recode(country_name, \"Tonga\" => \"TO\", \"Fiji\" => \"FJ\")",
    ["@assert all(.!ismissing(GEO_PICT))"],
    ["# Country name standardization for SDMX compliance"]
)
```

# See also
[`ScriptTemplate`](@ref), [`GeneratedScript`](@ref), [`build_transformation_steps`](@ref)
"""
struct TransformationStep
    step_name::String
    operation_type::String  # "read", "mutate", "pivot", "filter", "validate", "write"
    tidier_function::String # "@mutate", "@pivot_longer", etc.
    description::String
    source_columns::Vector{String}
    target_columns::Vector{String}
    transformation_logic::String
    validation_checks::Vector{String}
    comments::Vector{String}
end

"""
    ScriptTemplate

Template for generating specific types of transformation scripts.
"""
struct ScriptTemplate
    template_name::String
    description::String
    use_cases::Vector{String}
    required_packages::Vector{String}
    template_sections::Dict{String, String}
    placeholder_patterns::Dict{String, String}
    example_code::String
end

"""
    GeneratedScript

Complete generated transformation script with metadata.

# See also
"""
struct GeneratedScript
    script_name::String
    source_file::String
    target_schema::String
    generated_code::String
    transformation_steps::Vector{TransformationStep}
    estimated_complexity::Float64
    validation_notes::Vector{String}
    user_guidance::Vector{String}
    template_used::String
    generation_timestamp::String
end


# =================== CALLABLE STRUCT INTERFACE ===================


# Overload for DataSource input (automatically profiles the data)


"""
    create_standard_template() -> ScriptTemplate

Creates the standard transformation template.
"""
function create_standard_template()
    sections = Dict{String, String}(
        "header" => """
# SDMX Data Transformation Script
# Generated by SDMXer.jl on {{TIMESTAMP}}
# Source: {{SOURCE_FILE}}
# Target: {{TARGET_SCHEMA}}

using DataFrames, CSV, XLSX, Tidier, Statistics, Dates
""",

        "data_loading" => """
# === DATA LOADING ===
println("Loading source data...")
{{DATA_LOADING_CODE}}
println("Loaded \$(nrow(source_data)) rows and \$(ncol(source_data)) columns")
""",

        "data_exploration" => """
# === DATA EXPLORATION ===
println("Source data structure:")
println(describe(source_data))
println("\\nFirst few rows:")
println(first(source_data, 3))
""",

        "transformations" => """
# === DATA TRANSFORMATIONS ===
transformed_data = source_data |>
{{TRANSFORMATION_PIPELINE}}
""",

        "validation" => """
# === DATA VALIDATION ===
println("\\nValidation checks:")
{{VALIDATION_CHECKS}}
""",

        "output" => """
# === DATA OUTPUT ===
println("Writing SDMX-CSV output...")
{{OUTPUT_CODE}}
println("Transformation completed successfully!")
"""
    )

    placeholders = Dict{String, String}(
        "{{TIMESTAMP}}" => "generation_timestamp",
        "{{SOURCE_FILE}}" => "source_file",
        "{{TARGET_SCHEMA}}" => "target_schema",
        "{{DATA_LOADING_CODE}}" => "data_loading_logic",
        "{{TRANSFORMATION_PIPELINE}}" => "transformation_steps",
        "{{VALIDATION_CHECKS}}" => "validation_logic",
        "{{OUTPUT_CODE}}" => "output_logic"
    )

    example_code = """
# Example usage:
source_data = CSV.read("data.csv", DataFrame)
transformed_data = source_data |>
    @mutate(GEO_PICT = recode(country, "FJ" => "FJ", "VU" => "VU")) |>
    @mutate(TIME_PERIOD = string(year)) |>
    @select(GEO_PICT, TIME_PERIOD, OBS_VALUE = value)
"""

    return ScriptTemplate(
        "standard_transformation",
        "Standard SDMX transformation with validation and error handling",
        ["CSV to SDMX-CSV", "Simple data transformations", "Column mapping"],
        ["DataFrames", "CSV", "Tidier", "Statistics"],
        sections,
        placeholders,
        example_code
    )
end

"""
    create_pivot_template() -> ScriptTemplate

Creates template for pivot-heavy transformations.
"""
function create_pivot_template()
    sections = Dict{String, String}(
        "header" => """
# SDMX Pivot Transformation Script
# Generated by SDMXer.jl on {{TIMESTAMP}}
# Handles wide-to-long data pivoting

using DataFrames, CSV, XLSX, Tidier, Statistics, Dates
""",

        "data_loading" => """
# === DATA LOADING ===
{{DATA_LOADING_CODE}}
""",

        "pivot_analysis" => """
# === PIVOT ANALYSIS ===
# Detected time columns: {{TIME_COLUMNS}}
# Pivot strategy: {{PIVOT_STRATEGY}}
""",

        "transformations" => """
# === PIVOT TRANSFORMATIONS ===
transformed_data = source_data |>
{{PIVOT_TRANSFORMATION}}
{{POST_PIVOT_TRANSFORMATIONS}}
""",

        "validation" => """
# === VALIDATION ===
{{VALIDATION_CHECKS}}
""",

        "output" => """
# === OUTPUT ===
{{OUTPUT_CODE}}
"""
    )

    placeholders = Dict{String, String}(
        "{{TIME_COLUMNS}}" => "time_columns",
        "{{PIVOT_STRATEGY}}" => "pivot_strategy",
        "{{PIVOT_TRANSFORMATION}}" => "pivot_logic",
        "{{POST_PIVOT_TRANSFORMATIONS}}" => "post_pivot_steps"
    )

    return ScriptTemplate(
        "pivot_transformation",
        "Template for data requiring pivot operations",
        ["Wide-to-long transformation", "Time series data", "Multi-column pivoting"],
        ["DataFrames", "CSV", "XLSX", "Tidier"],
        sections,
        placeholders,
        ""
    )
end

"""
    create_excel_template() -> ScriptTemplate

Creates template for Excel multi-sheet processing.
"""
function create_excel_template()
    sections = Dict{String, String}(
        "header" => """
# SDMX Excel Multi-Sheet Transformation
# Generated by SDMXer.jl on {{TIMESTAMP}}

using DataFrames, XLSX, Tidier, Statistics
""",

        "excel_analysis" => """
# === EXCEL ANALYSIS ===
# Detected sheets: {{SHEET_NAMES}}
# Primary data sheet: {{PRIMARY_SHEET}}
# Metadata extraction: {{METADATA_INFO}}
""",

        "data_loading" => """
# === DATA LOADING ===
{{EXCEL_LOADING_CODE}}
""",

        "metadata_extraction" => """
# === METADATA EXTRACTION ===
{{METADATA_EXTRACTION_CODE}}
""",

        "transformations" => """
# === TRANSFORMATIONS ===
{{TRANSFORMATION_PIPELINE}}
"""
    )

    return ScriptTemplate(
        "excel_multi_sheet",
        "Template for Excel files with multiple sheets and metadata",
        ["Excel multi-sheet", "Metadata extraction", "Complex Excel structures"],
        ["DataFrames", "XLSX", "Tidier"],
        sections,
        Dict{String, String}(),
        ""
    )
end

"""
    create_csv_template() -> ScriptTemplate

Creates simple CSV template.
"""
function create_csv_template()
    sections = Dict{String, String}(
        "header" => """
# Simple SDMX CSV Transformation
# Generated by SDMXer.jl

using DataFrames, CSV, Tidier
""",

        "transformations" => """
# Load and transform data
source_data = CSV.read("{{SOURCE_FILE}}", DataFrame)

transformed_data = source_data |>
{{TRANSFORMATION_PIPELINE}}

# Save result
CSV.write("sdmx_output.csv", transformed_data)
"""
    )

    return ScriptTemplate(
        "simple_csv",
        "Simple CSV transformation template",
        ["Basic CSV processing", "Quick transformations"],
        ["DataFrames", "CSV", "Tidier"],
        sections,
        Dict{String, String}(),
        ""
    )
end


const DEFAULT_TEMPLATE_NAME = "standard_transformation"

"""
    default_templates() -> Dict{String, ScriptTemplate}

The four built-in script templates keyed by template name.
"""
function default_templates()
    return Dict{String, ScriptTemplate}(
        "standard_transformation" => create_standard_template(),
        "pivot_transformation" => create_pivot_template(),
        "excel_multi_sheet" => create_excel_template(),
        "simple_csv" => create_csv_template()
    )
end

"""
    select_template(source_profile::SourceDataProfile; template_name::String="") -> ScriptTemplate

Pick the built-in template that fits the source profile, or the named one.
"""
function select_template(source_profile::SourceDataProfile; template_name::String="")
    templates = default_templates()
    if !isempty(template_name) && haskey(templates, template_name)
        return templates[template_name]
    end
    if length(source_profile.suggested_time_columns) > 0 && source_profile.column_count > 5
        return templates["pivot_transformation"]
    end
    if source_profile.file_type == "csv" && source_profile.column_count <= 8
        return templates["simple_csv"]
    end
    return templates[DEFAULT_TEMPLATE_NAME]
end

"""
    build_transformation_steps(mapping_result::AdvancedMappingResult,
                              source_profile::SourceDataProfile,
                              target_schema::DataflowSchema) -> Vector{TransformationStep}

Builds detailed transformation steps from mapping results.
"""
function build_transformation_steps(mapping_result::AdvancedMappingResult,
                                   source_profile::SourceDataProfile,
                                   target_schema::DataflowSchema)

    steps = Vector{TransformationStep}()

    # Step 1: Data loading
    push!(steps, TransformationStep(
        "data_loading",
        "read",
        "CSV.read / XLSX.readtable",
        "Load source data from $(source_profile.file_type) file",
        String[],
        String[],
        get_loading_code(source_profile),
        String[],
        ["Load the source data file with appropriate function"]
    ))

    # Step 2: Data exploration (optional)
    if mapping_result.quality_score < 0.8
        push!(steps, TransformationStep(
            "data_exploration",
            "explore",
            "describe / first",
            "Explore data structure and identify issues",
            collect(String[col.name for col in source_profile.columns]),
            String[],
            "describe(source_data)",
            String[],
            ["Review data structure", "Check for data quality issues", "Understand value distributions"]
        ))
    end

    # Step 3: Column mappings and transformations
    for mapping in mapping_result.mappings
        step_name = "map_$(mapping.source_column)_to_$(mapping.target_column)"

        if mapping.suggested_transformation !== nothing
            # Complex transformation needed
            push!(steps, TransformationStep(
                step_name,
                "mutate",
                "@mutate",
                "Transform $(mapping.source_column) to $(mapping.target_column)",
                [mapping.source_column],
                [mapping.target_column],
                generate_transformation_logic(mapping),
                ["Check for missing values", "Validate transformation results"],
                ["$(mapping.confidence_level) confidence mapping", "$(mapping.match_type) match"]
            ))
        else
            # Simple column rename/select
            push!(steps, TransformationStep(
                step_name,
                "select",
                "@select",
                "Map $(mapping.source_column) to $(mapping.target_column)",
                [mapping.source_column],
                [mapping.target_column],
                "$(mapping.target_column) = $(mapping.source_column)",
                String[],
                ["Direct column mapping"]
            ))
        end
    end

    # Step 4: Handle missing required columns
    required_cols = get_required_columns(target_schema)
    mapped_targets = Set([m.target_column for m in mapping_result.mappings])
    missing_required = setdiff(Set(required_cols), mapped_targets)

    if !isempty(missing_required)
        push!(steps, TransformationStep(
            "handle_missing_columns",
            "mutate",
            "@mutate",
            "Handle missing required columns",
            String[],
            collect(missing_required),
            "# TODO: Add logic for missing columns: $(join(missing_required, ", "))",
            ["Ensure all required columns are present"],
            ["Manual intervention needed for unmapped required columns"]
        ))
    end

    # Step 5: Data validation
    if any(m.confidence_level <= MEDIUM for m in mapping_result.mappings)
        push!(steps, TransformationStep(
            "data_validation",
            "validate",
            "custom validation",
            "Validate transformation results",
            String[],
            String[],
            create_validation_logic(mapping_result, target_schema),
            ["Check data completeness", "Validate against SDMX requirements"],
            ["Review low-confidence mappings", "Check for data quality issues"]
        ))
    end

    # Step 6: Output
    push!(steps, TransformationStep(
        "data_output",
        "write",
        "CSV.write",
        "Write SDMX-compliant CSV output",
        String[],
        String[],
        "CSV.write(\"sdmx_output.csv\", transformed_data)",
        ["Verify output format compliance"],
        ["Save result as SDMX-CSV format"]
    ))

    return steps
end


"""
    get_loading_code(source_profile::SourceDataProfile) -> String

Generates appropriate data loading code based on file type.
"""
function get_loading_code(source_profile::SourceDataProfile)
    if source_profile.file_type == "csv"
        return """source_data = CSV.read("$(source_profile.file_path)", DataFrame)"""
    elseif source_profile.file_type in ["xlsx", "xls"]
        return """source_data = XLSX.readtable("$(source_profile.file_path)", 1) |> DataFrame
# Note: Adjust sheet number/name as needed"""
    else
        return "# TODO: Add appropriate loading code for $(source_profile.file_type) files"
    end
end

"""
    generate_transformation_logic(mapping::MappingCandidate) -> String

Generates Tidier.jl transformation logic for a specific mapping.
"""
function generate_transformation_logic(mapping::MappingCandidate)
    if mapping.suggested_transformation !== nothing
        return mapping.suggested_transformation
    end

    # Generate basic transformation based on mapping type
    if mapping.match_type == "exact"
        return "$(mapping.target_column) = $(mapping.source_column)"
    elseif mapping.match_type == "fuzzy" || mapping.match_type == "name_fuzzy"
        return "$(mapping.target_column) = $(mapping.source_column)  # Review fuzzy match"
    else
        return "$(mapping.target_column) = $(mapping.source_column)  # TODO: Verify mapping"
    end
end

"""
    create_validation_logic(mapping_result::AdvancedMappingResult,
                           target_schema::DataflowSchema) -> String

Creates validation logic for the transformation.
"""
function create_validation_logic(mapping_result::AdvancedMappingResult,
                                target_schema::DataflowSchema)
    validation_code = """
# Check required columns are present
required_cols = $(get_required_columns(target_schema))
missing_cols = setdiff(required_cols, names(transformed_data))
if !isempty(missing_cols)
    @warn "Missing required columns: \$missing_cols"
end

# Check for missing values in key columns
for col in names(transformed_data)
    missing_count = sum(ismissing.(transformed_data[!, col]))
    if missing_count > 0
        println("Column '\$col' has \$missing_count missing values")
    end
end

println("Validation completed.")"""

    return validation_code
end


"""
    calculate_script_complexity(transformation_steps::Vector{TransformationStep},
                                mapping_result::AdvancedMappingResult) -> Float64

Calculates estimated complexity of the generated script.
"""
function calculate_script_complexity(transformation_steps::Vector{TransformationStep},
                                    mapping_result::AdvancedMappingResult)

    complexity = 0.0

    # Base complexity from number of transformation steps
    complexity += length(transformation_steps) * 0.1

    # Complexity from transformation types
    for step in transformation_steps
        if step.operation_type in ["pivot", "validate"]
            complexity += 0.2
        elseif step.operation_type in ["mutate"]
            complexity += 0.1
        end
    end

    # Complexity from mapping quality
    complexity += (1.0 - mapping_result.quality_score) * 0.3

    # Complexity from transformation needs
    complex_transformations = sum([m.suggested_transformation !== nothing for m in mapping_result.mappings])
    complexity += complex_transformations * 0.05

    return min(1.0, complexity)
end

"""
    validate_generated_script(script::GeneratedScript) -> Dict{String, Any}

Validates the generated script for common issues.
"""
function validate_generated_script(script::GeneratedScript)
    validation = Dict{String, Any}(
        "syntax_issues" => String[],
        "missing_elements" => String[],
        "recommendations" => String[],
        "overall_quality" => "unknown"
    )

    code = script.generated_code

    # Check for required imports
    required_packages = ["DataFrames", "Tidier"]
    for package in required_packages
        if !occursin("using $package", code) && !occursin("import $package", code)
            push!(validation["missing_elements"], "Missing import for $package")
        end
    end

    # Check for Tidier.jl usage
    tidier_functions = ["@mutate", "@select", "@filter", "@pivot_longer", "@pivot_wider"]
    tidier_used = any(func -> occursin(func, code), tidier_functions)
    if !tidier_used
        push!(validation["missing_elements"], "No Tidier.jl functions detected")
    end

    # Check for data loading
    if !occursin("CSV.read", code) && !occursin("XLSX.read", code)
        push!(validation["missing_elements"], "No data loading code detected")
    end

    # Check for output
    if !occursin("CSV.write", code) && !occursin("write", code)
        push!(validation["missing_elements"], "No data output code detected")
    end

    # Recommendations
    if script.estimated_complexity > 0.7
        push!(validation["recommendations"], "High complexity script - consider breaking into smaller steps")
    end

    if length(script.validation_notes) > 3
        push!(validation["recommendations"], "Multiple validation concerns - thorough testing recommended")
    end

    # Overall quality assessment
    issues = length(validation["syntax_issues"]) + length(validation["missing_elements"])
    if issues == 0
        validation["overall_quality"] = "good"
    elseif issues <= 2
        validation["overall_quality"] = "acceptable"
    else
        validation["overall_quality"] = "needs_work"
    end

    return validation
end

"""
    preview_script_output(script::GeneratedScript; max_lines::Int = 50) -> String

Creates a preview of the generated script for user review.
"""
function preview_script_output(script::GeneratedScript; max_lines::Int = 50)
    preview = """
=== GENERATED SCRIPT PREVIEW ===
Script: $(script.script_name)
Template: $(script.template_used)
Generated: $(script.generation_timestamp)
Complexity: $(round(script.estimated_complexity, digits=2))

Source: $(script.source_file)
Target: $(script.target_schema)

=== TRANSFORMATION STEPS ($(length(script.transformation_steps))) ===
"""

    for (i, step) in enumerate(script.transformation_steps)
        preview *= "$(i). $(step.step_name): $(step.description)\n"
    end

    if !isempty(script.validation_notes)
        preview *= "\n=== VALIDATION NOTES ===\n"
        for note in script.validation_notes
            preview *= "⚠ $note\n"
        end
    end

    if !isempty(script.user_guidance)
        preview *= "\n=== USER GUIDANCE ===\n"
        for guidance in script.user_guidance
            preview *= "💡 $guidance\n"
        end
    end

    preview *= "\n=== CODE PREVIEW (first $max_lines lines) ===\n"
    code_lines = split(script.generated_code, '\n')
    preview_lines = code_lines[1:min(max_lines, length(code_lines))]
    preview *= join(preview_lines, '\n')

    if length(code_lines) > max_lines
        preview *= "\n... ($(length(code_lines) - max_lines) more lines)"
    end

    return preview
end
